Web/MyTvSeries.Web/Models/Seasons/EpisodeOnSeasonViewModel.cs
using MyTvSeries.Web.Models.Enums;

namespace MyTvSeries.Web.Models.Seasons
{
    public class EpisodeOnSeasonViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Overview { get; set; }
        public string Aired { get; set; }
        public long? EpisodeNumber { get; set; }
        public decimal EpisodeSiteRating { get; set; }
        public EpisodeRating Rating { get; set; }

    }
}

Web/MyTvSeries.Web/Models/Seasons/SeasonDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyTvSeries.Web.Models.Seasons
{
    public class SeasonDetailViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Overview { get; set; }
        public int NumberOfEpisodes { get; set; }
        public int? SeasonNumber { get; set; }
        public string AiredFrom { get; set; }
        public long SeriesId { get; set; }
        public List<EpisodeOnSeasonViewModel> Episodes { get; set; }
    }
}

Web/MyTvSeries.Web/Models/Seasons/SeasonIndexListViewModel.cs
using System.Collections.Generic;

namespace MyTvSeries.Web.Models.Seasons
{
    public class SeasonIndexListViewModel
    {
        public long? SeriesId { get; set; }
        public List<SeasonIndexViewModel> ViewModels { get; set; }
    }
}

Web/MyTvSeries.Web/Models/Seasons/SeasonIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyTvSeries.Web.Models.Seasons
{
    public class SeasonIndexViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }

        [Display(Name = "Season number")]
        public int? SeasonNumber { get; set; }

        [Display(Name = "Number of episodes")]
        public int? NumberOfEpisodes { get; set; }

        [Display(Name = "Aired from")]
        public string AiredFrom { get; set; }

        [Display(Name = "Rating")]
        public string Rating { get; set; }
    }
}

Web/MyTvSeries.Web/Controllers/SeriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Pages.Internal.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyTvSeries.Domain.Ef;
using MyTvSeries.Domain.Entities;
using MyTvSeries.Domain.Enums;
using MyTvSeries.Domain.Identity;
using MyTvSeries.Web.Models.Enums;
using MyTvSeries.Web.Models.Series;
using X.PagedList;

namespace MyTvSeries.Web.Controllers
{
    public class SeriesController : Controller
    {
        private readonly TvSeriesContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SeriesController(TvSeriesContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Series
        public async Task<IActionResult> Index(int? page, string keyword, string sortBy, string ChosenGenre, string ChosenStatus)
        {
            IQueryable<Series> allSeries = null;
            if (!string.IsNullOrEmpty(keyword))
            {
                allSeries = _context.Series
                    .Include(x => x.SeriesGenres)
                    .Where(x => x.Name.Contains(keyword)).AsQueryable();
            }
            else
            {
                allSeries = _context.Series
                    .Include(x => x.SeriesGenres)
                    .AsQueryable();
            }

            if (!string.IsNullOrEmpty(ChosenGenre))
            {
                allSeries = allSeries.Where(x => x.SeriesGenres.Any(y => y.Genre.Name == ChosenGenre));
            }

            if (!string.IsNullOrEmpty(ChosenStatus))
            {
                Enum.TryParse(ChosenStatus, out SeriesStatus myStatus);
                allSeries = allSeries.Where(x => x.Status == myStatus);
            }

            switch (sortBy)
            {
                case "Rating":
                    allSeries = allSeries.OrderByDescending(x => x.UserRating);
                    break;
                case "Name":
                    allSeries = allSeries.OrderBy(x => x.Name);
                    break;
                default:
                    break;
            }

            var pageNumber = page ?? 1;

            var pageSize = 25;

            var pagedSeries = await allSeries.ToPagedListAsync(pageNumber, pageSize);

            var viewModels = new List<SeriesIndexViewModel>();

            foreach (var series in pagedSeries)
            {
                var viewModel = new SeriesIndexViewModel
                {
                    Id = series.Id,
                    Name = series.Name,
                    UserRating = series.UserRating,
                    PosterContent = series.PosterContent
                };
                viewModels.Add(viewModel);
            }

            var pagedViewModels = new StaticPagedList<SeriesIndexViewModel>(viewModels, pageNumber, pageSize, pagedSeries.TotalItemCount);

            var viewModelWithKeyword = new SeriesIndexSearchViewModel
            {
                ViewModels = pagedViewModels,
                Keyword = keyword,
            };

            if (!string.IsNullOrEmpty(ChosenGenre))
            {
                viewModelWithKeyword.ChosenGenre = ChosenGenre;
            }

            if (!string.IsNullOrEmpty(ChosenStatus))
            {
                viewModelWithKeyword.ChosenStatus = ChosenStatus;
            }

            viewModelWithKeyword.Genres = await _context.Genres.Select(x => x.Name).ToListAsync();
            viewModelWithKeyword.Statuses = Enum.GetNames(typeof(SeriesStatus)).ToList();

            return View(viewModelWithKeyword);
        }

        // GET: Series/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var series = await _context.Series.Include(x => x.Seasons)
                .Include(x => x.SeriesCharacters)
                .Include(x => x.Crews)
                .Include(x => x.SeriesReviews)
                .ThenInclude(x => x.UserReviews)
                .Include(x => x.SeriesGenres)
                .ThenInclude(x => x.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (series == null)
            {
                return NotFound();
            }


            // TODO move to mapper
            var viewModel = new UserSeriesDetailViewModel
            {
                SeriesId = series.Id,
                Name = series.Name,
                OriginalName = series.OriginalName,
                SiteRating = series.UserRating,
                UserVotes = series.UserVotes,
                Overview = series.Overview,
                Status = series.Status,
                AiredFrom = series.AiredFrom,
                AiredTo = series.AiredTo,
                AirDayOfWeek = series.AirDayOfWeek,
                AirTime = series.AirTime,
                NumberOfSeasons = series.NumberOfSeasons,
                NumberOfEpisodes = series.NumberOfEpisodes,
                EpisodeRuntime = series.EpisodeRuntime,
                TotalRuntime = series.TotalRuntime,
                PosterContent = series.PosterContent,
                Genres = new List<Genre>(),
                SeasonSeries = new List<SeasonSeriesDetailViewModel>(),
                Cast = new List<CastSeriesDetailViewModel>(),
                Crew = new List<CrewSeriesDetailViewModel>(),
                Reviews = new List<SeriesReviewDetailViewModel>()
            };

            // GENRES
            foreach (var seriesGenre in series.SeriesGenres)
            {
                viewModel.Genres.Add(seriesGenre.Genre);
            }

            //SEASONS
            var seasonsOnView = 5;
            var seasons = series.Seasons.OrderBy(x => x.SeasonNumber).ToList();

            for (int i = 0; i < seasonsOnView; i++)
            {
                if (i < seasons.Count)
                {
                    var season = seasons.ElementAt(i);
                    var seasonViewModel = new SeasonSeriesDetailViewModel
                    {
                        SeasonId = season.Id,
                        NumberOfEpisodes = season.NumberOfEpisodes,
                        SeasonName = season.Name,
                        SeasonNumber = season.SeasonNumber,
                    };
                    if (season.AiredFrom != null)
                        seasonViewModel.AiredFrom = season.AiredFrom.Value.ToString("dd MMMM yyyy");

                    viewModel.SeasonSeries.Add(seasonViewModel);
                }
                else
                    break;
            }
            

            viewModel.IsMoreSeasons = seasons.Count > viewModel.SeasonSeries.Count;

            //CAST

            for (int i = 0; i < 4; i++)
            {
                if (i < series.SeriesCharacters.Count)
                {
                    var characterId = series.SeriesCharacters.ElementAt(i).CharacterId;
                    var castMember = await _context.Characters
                        .Include(x => x.Person)
                        .FirstOrDefaultAsync(x => x.Id == characterId);                   

                    var castViewModel = new CastSeriesDetailViewModel
                    {
                        PersonId = castMember.PersonId,
                        Character = castMember.Name,
                        Name = castMember.Person.Name,
                        Picture = castMember.Person.PosterContent
                    };

                    viewModel.Cast.Add(castViewModel);
                }
                else
                    break;
            }

            viewModel.IsMoreCast = series.SeriesCharacters.Count > viewModel.Cast.Count;

            // Crew

            for (int i = 0; i < 4; i++)
            {
                if (i < series.Crews.Count)
                {
                    var crew = series.Crews.ElementAt(i);
                    var personId = crew.PersonId;
                    var person = await _context.Persons
                        .FirstOrDefaultAsync(x => x.Id == personId);

                    var crewViewModel = new CrewSeriesDetailViewModel
                    {
                        PersonId = personId,
                        Name = person.Name,
                        Job = crew.Job,
                        Department = crew.Department,                  
                        Picture = person.PosterContent
                    };

                    viewModel.Crew.Add(crewViewModel);
                }
                else
                    break;
            }

            viewModel.IsMoreCrew = series.Crews.Count > viewModel.Crew.Count;

            // REVIEWS

            for (int i = 0; i < 3; i++)
            {
                if (i < series.SeriesReviews.Count)
                {
                    var review = series.SeriesReviews.ElementAt(i);

                    var reviewViewModel = new SeriesReviewDetailViewModel()
                    {
                        Id = review.Id,
                        Content = review.Content,
                        Likes = review.Likes,
                        WrittenOn = review.CreatedAt
                    };

                    if (review.LastChangedAt != null)
                    {
                        reviewViewModel.WrittenOn = review.LastChangedAt.Value;
                    }

                    var user = await _userManager.FindByIdAsync(review.UserId);
                    reviewViewModel.Username = user.UserName;

                    var userRating = await _context.UsersSeries
                        .Where(x => x.SeriesId == id && x.UserId == user.Id)

Web/MyTvSeries.Web/Views/Seasons/Create.cshtml
@model MyTvSeries.Domain.Entities.Season

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Season</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MovieDbId" class="control-label"></label>
                <input asp-for="MovieDbId" class="form-control" />
                <span asp-validation-for="MovieDbId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeriesId" class="control-label"></label>
                <select asp-for="SeriesId" class ="form-control" asp-items="ViewBag.SeriesId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Overview" class="control-label"></label>
                <input asp-for="Overview" class="form-control" />
                <span asp-validation-for="Overview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeasonNumber" class="control-label"></label>
                <input asp-for="SeasonNumber" class="form-control" />
                <span asp-validation-for="SeasonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AiredFrom" class="control-label"></label>
                <input asp-for="AiredFrom" class="form-control" />
                <span asp-validation-for="AiredFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfEpisodes" class="control-label"></label>
                <input asp-for="NumberOfEpisodes" class="form-control" />
                <span asp-validation-for="NumberOfEpisodes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsImportEnabled" /> @Html.DisplayNameFor(model => model.IsImportEnabled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastChangedBy" class="control-label"></label>
                <input asp-for="LastChangedBy" class="form-control" />
                <span asp-validation-for="LastChangedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastChangedAt" class="control-label"></label>
                <input asp-for="LastChangedAt" class="form-control" />
                <span asp-validation-for="LastChangedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Web/MyTvSeries.Web/Views/Seasons/Delete.cshtml
@model MyTvSeries.Domain.Entities.Season

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Season</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieDbId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MovieDbId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Series)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Series.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Overview)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Overview)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SeasonNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SeasonNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AiredFrom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AiredFrom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NumberOfEpisodes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfEpisodes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsImportEnabled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsImportEnabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastChangedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastChangedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastChangedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastChangedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/MyTvSeries.Web/Views/Seasons/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using MyTvSeries.Domain.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model MyTvSeries.Web.Models.Seasons.SeasonDetailViewModel
@using MyTvSeries.Web.Models.Enums

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.HiddenFor(x => x.SeriesId)
@Html.HiddenFor(x => x.Id)

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div id="episodesChart" style="height: 400px;">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <h2></h2>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-9">
                    <h1>@Model.Name</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Overview)
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <h2>Episodes</h2>
            <div class="panel panel-default">
                <ul class="list-group">
                    @for (int i = 0; i < Model.Episodes.Count; i++)
                    {
                        <li class="list-group-item">
                            <header>
                                <h2>@Model.Episodes[i].EpisodeNumber. @Model.Episodes[i].Name</h2>
                                <span class="text-right">
                                    @Model.Episodes[i].Aired
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        @Html.DropDownListFor(x => x.Episodes[i].Rating, Html.GetEnumSelectList<EpisodeRating>(), new { onchange = "rateEpisode(this);", episodeId = @Model.Episodes[i].Id })
                                    }
                                </span>
                            </header>
                            <div>@Model.Episodes[i].Overview</div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-controller="Series" asp-action="Details" asp-route-id="@Model.SeriesId">
        Back to Series
    </a>
</div>

<script type="text/javascript">

    window.onload = function () {
        var episodesChart = new CanvasJS.Chart("episodesChart", {
            theme: "theme2",
            animationEnabled: true,
            title: {
                text: "Episodes scores"
            },
            axisY: {
                includeZero: false,
                maximum: 10,
                minimum: 1
            },
            data: [
                {
                    type: "line", //change type to bar, line, area, pie, etc
                    dataPoints: @Html.Raw(ViewBag.DataPointsLine)
                }
            ]
        });
        episodesChart.render();
    };
</script>

Web/MyTvSeries.Web/Views/Seasons/Edit.cshtml
@model MyTvSeries.Domain.Entities.Season

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Season</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieDbId" class="control-label"></label>
                <input asp-for="MovieDbId" class="form-control" />
                <span asp-validation-for="MovieDbId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeriesId" class="control-label"></label>
                <select asp-for="SeriesId" class="form-control" asp-items="ViewBag.SeriesId"></select>
                <span asp-validation-for="SeriesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Overview" class="control-label"></label>
                <input asp-for="Overview" class="form-control" />
                <span asp-validation-for="Overview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeasonNumber" class="control-label"></label>
                <input asp-for="SeasonNumber" class="form-control" />
                <span asp-validation-for="SeasonNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AiredFrom" class="control-label"></label>
                <input asp-for="AiredFrom" class="form-control" />
                <span asp-validation-for="AiredFrom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfEpisodes" class="control-label"></label>
                <input asp-for="NumberOfEpisodes" class="form-control" />
                <span asp-validation-for="NumberOfEpisodes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsImportEnabled" /> @Html.DisplayNameFor(model => model.IsImportEnabled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastChangedBy" class="control-label"></label>
                <input asp-for="LastChangedBy" class="form-control" />
                <span asp-validation-for="LastChangedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastChangedAt" class="control-label"></label>
                <input asp-for="LastChangedAt" class="form-control" />
                <span asp-validation-for="LastChangedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Web/MyTvSeries.Web/Views/Seasons/Index.cshtml
@model MyTvSeries.Web.Models.Seasons.SeasonIndexListViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Seasons</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div id="seasonsChart" style="height: 400px;">
            </div>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ViewModels.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewModels.FirstOrDefault().AiredFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewModels.FirstOrDefault().SeasonNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewModels.FirstOrDefault().NumberOfEpisodes)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ViewModels)
        {
        <tr>
            <td>
                <div class="col-md-6">
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </div>
            </td>
            <td>
                <div class="col-md-6">
                    @Html.DisplayFor(modelItem => item.AiredFrom)
                </div>
            </td>
            <td>
                <div class="col-md-6">
                    @Html.DisplayFor(modelItem => item.SeasonNumber)
                </div>
            </td>
            <td>
                <div class="col-md-6">
                    @Html.DisplayFor(modelItem => item.NumberOfEpisodes)
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>

<script type="text/javascript">

    window.onload = function () {
        var seasonsChart = new CanvasJS.Chart("seasonsChart", {
            theme: "theme2",
            animationEnabled: true,
            title: {
                text: "Season scores"
            },
            axisY: {
                includeZero: false,
                maximum: 10,
                minimum: 1
            },
            data: [
                {
                    type: "line", //change type to bar, line, area, pie, etc
                    dataPoints: @Html.Raw(ViewBag.DataPointsLine)
                }
            ]
        });
        seasonsChart.render();
    };
</script>